- name: Build
        run: npm run build
        env:
          VITE_PIXABAY_API_KEY: ${{ secrets.VITE_PIXABAY_API_KEY }}

      - name: Setup Pages
        uses: actions/configure-pages@v4

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          
          path: './dist' 

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4